logging.level.com.vulinh:
  configuration.cache.Common: DEBUG
  service:
    taxcalculator.TaxService: DEBUG
    user.UserValidationService: DEBUG
    post:
      PostValidationService: DEBUG
      PostEditValidationService: DEBUG
    category.CategoryService: DEBUG
    eventlistener.CustomEventListener: DEBUG
  configuration:
    SecurityConfig: DEBUG
    cache.FromUserSessionEntityKeyGenerator: DEBUG