logging.level:
  com.vulinh:
    configuration.cache.Common: DEBUG
    service:
      event.EventService: DEBUG
      taxcalculator.TaxService: DEBUG
      user.UserValidationService: DEBUG
      post:
        PostValidationService: DEBUG
        PostEditValidationService: DEBUG
      category.CategoryService: DEBUG
    configuration.com.vulinh.configuration.SecurityConfiguration: DEBUG
    # org.springframework.security.oauth2: TRACE
    # Remove the comment sign for extra debugging information