# Disable P6SPY logging on production (hypothetical)
decorator.datasource.p6spy.enable-logging: false
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
# Not running on production (hypothetical)
spring.liquibase.enabled: false